---
deployment:
  tasks:
    - export DEPLOYPATH=/home/wedangs2/blobv2.theblobstudio.com/
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp home.html $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    # - /bin/cp -R js $DEPLOYPATH