---
deployment:
  tasks:
    - export DEPLOYPATH=/home/wedangs2/blobv2.theblobstudio.com/
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp arka.html $DEPLOYPATH
    - /bin/cp butabi.html $DEPLOYPATH
    - /bin/cp contacts.html $DEPLOYPATH
    - /bin/cp home.html $DEPLOYPATH
    - /bin/cp klique.html $DEPLOYPATH
    - /bin/cp littlelayers.html $DEPLOYPATH
    - /bin/cp naisu.html $DEPLOYPATH
    - /bin/cp ourworks.html $DEPLOYPATH
    - /bin/cp service.html $DEPLOYPATH
    - /bin/cp setjang.html $DEPLOYPATH
    - /bin/cp 404.html $DEPLOYPATH
    # - /bin/cp -R js $DEPLOYPATH